# ISM-V2-PROVENANCE: EAA67EB5ADAA4B0C3CE250BE
# Repository provenance: ISpooferMotion V2 / IncredibroXP.
# Attribution marker only; preserve any upstream author/license notices.

version: 2
updates:
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'cargo'
    directory: '/src-tauri'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

# ISM-V2-PROVENANCE-END: EAA67EB5ADAA4B0C3CE250BE
