// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from '@tauri-apps/api/core';

/** Commands */
export const commands = {
  /**
   *  Takes raw Roblox XML (`<roblox!>...`) containing a `KeyframeSequence`
   *  and converts it into a `RobloxAnimationClip` for the frontend.
   */
  parseAnimationData: (xml: string) =>
    typedError<
      {
        loop: boolean;
        priority: number;
        duration: number | null;
        keyframes: RobloxKeyframe[];
      } | null,
      string
    >(__TAURI_INVOKE('parse_animation_data', { xml })),
  /**  Paginated fetch of a user or group's public inventory from Roblox. */
  fetchAssets: (query: FetchAssetsRequest) =>
    typedError<FetchAssetsResponse, AppError>(__TAURI_INVOKE('fetch_assets', { query })),
  /**  Grabs the 420x420 PNG thumbnail for a specific asset ID directly from Roblox. */
  fetchRobloxThumbnail: (assetId: string) =>
    typedError<string | null, AppError>(__TAURI_INVOKE('fetch_roblox_thumbnail', { assetId })),
  /**
   *  Downloads the raw binary or XML representation of a Roblox animation asset.
   *
   *  Converts binary-format animations (`<roblox!`) into readable XML text before returning.
   */
  fetchAnimationXml: (assetId: string, cookie: string | null, placeId: string | null) =>
    typedError<string | null, AppError>(
      __TAURI_INVOKE('fetch_animation_xml', { assetId, cookie, placeId }),
    ),
  getCookieFromRobloxStudio: (userId: string | null) =>
    typedError<string | null, AppError>(
      __TAURI_INVOKE('get_cookie_from_roblox_studio', { userId }),
    ),
  getCookieFromAutoDetect: (userId: string | null) =>
    typedError<string | null, AppError>(__TAURI_INVOKE('get_cookie_from_auto_detect', { userId })),
  deleteSavedRobloxProfileCookie: (userId: string) =>
    typedError<boolean, AppError>(__TAURI_INVOKE('delete_saved_roblox_profile_cookie', { userId })),
  getCsrfToken: (cookie: string) =>
    typedError<string, AppError>(__TAURI_INVOKE('get_csrf_token', { cookie })),
  getAuthenticatedUserId: (cookie: string) =>
    typedError<string, AppError>(__TAURI_INVOKE('get_authenticated_user_id', { cookie })),
  getRobloxUserInfo: (userId: string) =>
    typedError<RobloxUserInfo, AppError>(__TAURI_INVOKE('get_roblox_user_info', { userId })),
  getRobloxUserAvatar: (userId: string) =>
    typedError<string, AppError>(__TAURI_INVOKE('get_roblox_user_avatar', { userId })),
  getManageableGroups: (cookie: string) =>
    typedError<RobloxGroup[], AppError>(__TAURI_INVOKE('get_manageable_groups', { cookie })),
  getGroupIcon: (groupId: string) =>
    typedError<string, AppError>(__TAURI_INVOKE('get_group_icon', { groupId })),
  getGroupIconsBatch: (groupIds: string[]) =>
    typedError<{ [key in string]: string }, AppError>(
      __TAURI_INVOKE('get_group_icons_batch', { groupIds }),
    ),
  detectOpencloudApiKeyOwner: (key: string) =>
    typedError<ApiKeyOwnerDetectResult, AppError>(
      __TAURI_INVOKE('detect_opencloud_api_key_owner', { key }),
    ),
  validateOpencloudApiKey: (key: string) =>
    typedError<boolean, AppError>(__TAURI_INVOKE('validate_opencloud_api_key', { key })),
  getAuthMetadata: () => typedError<string, AppError>(__TAURI_INVOKE('get_auth_metadata')),
  /**
   *  Destroys the splashscreen window and spawns the main frameless React window.
   *
   *  This avoids the ugly white flash during React initialization.
   */
  closeSplashscreen: () => __TAURI_INVOKE<void>('close_splashscreen'),
  /**
   *  Automatically installs or updates the ISpooferMotion Luau plugin in Studio's local plugins folder.
   *
   *  The `.rbxmx` plugin file is bundled into the Tauri binary at compile-time.
   *  When the app boots, this copies it directly into Roblox plugins folders.
   */
  syncRobloxPlugin: () => typedError<boolean, AppError>(__TAURI_INVOKE('sync_roblox_plugin')),
  /**  Opens the application's config directory in the native file explorer. */
  openDataFolder: () => typedError<boolean, AppError>(__TAURI_INVOKE('open_data_folder')),
  /**  Deletes all cached data (like downloaded thumbnails and audio files). */
  clearAppCache: () => typedError<boolean, AppError>(__TAURI_INVOKE('clear_app_cache')),
  /**
   *  Downloads an audio asset from Roblox to the local cache and returns its path.
   *
   *  The frontend uses this to stream audio via HTML5 `<audio>` since we can't
   *  reliably bypass Roblox's CORS policies directly in the browser context.
   */
  playRobloxAudio: (assetId: string, cookie: string | null, enableCache: boolean | null) =>
    typedError<string, AppError>(
      __TAURI_INVOKE('play_roblox_audio', { assetId, cookie, enableCache }),
    ),
  /**  Triggers a native desktop notification. */
  showNotification: (options: NotificationOptions) =>
    typedError<boolean, AppError>(__TAURI_INVOKE('show_notification', { options })),
  /**  Spawns a detached native terminal window that tails the latest log file. */
  openDevConsole: () => typedError<boolean, AppError>(__TAURI_INVOKE('open_dev_console')),
  windowMinimize: () => __TAURI_INVOKE<void>('window_minimize'),
  windowClose: () => __TAURI_INVOKE<void>('window_close'),
  quitApp: () => __TAURI_INVOKE<void>('quit_app'),
  getAppVersion: () => __TAURI_INVOKE<string>('get_app_version'),
  getReleaseSource: () => __TAURI_INVOKE<string>('get_release_source'),
  getRuntimeInfo: () => __TAURI_INVOKE<string>('get_runtime_info'),
  openExternal: (url: string) =>
    typedError<boolean, AppError>(__TAURI_INVOKE('open_external', { url })),
  selectFolder: () => typedError<string | null, AppError>(__TAURI_INVOKE('select_folder')),
  uninstallApp: () => typedError<boolean, AppError>(__TAURI_INVOKE('uninstall_app')),
  clearPluginCache: () => typedError<boolean, AppError>(__TAURI_INVOKE('clear_plugin_cache')),
  openFrontendDevtools: () => __TAURI_INVOKE<void>('open_frontend_devtools'),
  /**
   *  Updates the proxy URL used for outbound Roblox/API calls. Pass an empty
   *  string or `None` to fall back to the OS system proxy (Windows WinINET, which
   *  VPN "proxy mode" apps like Happ set). Called from the frontend on startup and
   *  whenever the Proxy URL setting changes.
   */
  setProxyUrl: (url: string | null) => __TAURI_INVOKE<boolean>('set_proxy_url', { url }),
  runSpooferAction: (data: SpooferActionRequest) =>
    typedError<null, AppError>(__TAURI_INVOKE('run_spoofer_action', { data })),
  spooferPause: (jobId: string) => __TAURI_INVOKE<boolean>('spoofer_pause', { jobId }),
  spooferResume: (jobId: string) => __TAURI_INVOKE<boolean>('spoofer_resume', { jobId }),
  spooferCancel: (jobId: string) => __TAURI_INVOKE<boolean>('spoofer_cancel', { jobId }),
  checkSession: () => typedError<string, AppError>(__TAURI_INVOKE('check_session')),
  appendDebugLog: (level: string, source: string | null, message: string) =>
    typedError<boolean, AppError>(__TAURI_INVOKE('append_debug_log', { level, source, message })),
  openLogsFolder: () => typedError<boolean, AppError>(__TAURI_INVOKE('open_logs_folder')),
  openPluginsFolder: () => typedError<boolean, AppError>(__TAURI_INVOKE('open_plugins_folder')),
  copyDebugInfo: (context: string | null) =>
    typedError<string, AppError>(__TAURI_INVOKE('copy_debug_info', { context })),
  exportSupportReport: (context: string | null) =>
    typedError<string, AppError>(__TAURI_INVOKE('export_support_report', { context })),
  getRobloxProfile: (context: ProfileRequest) =>
    typedError<string, AppError>(__TAURI_INVOKE('get_roblox_profile', { context })),
  fetchAudioQuota: (cookie: string | null, autoDetect: boolean | null, context: string | null) =>
    typedError<string, AppError>(
      __TAURI_INVOKE('fetch_audio_quota', { cookie, autoDetect, context }),
    ),
  loadRendererSettings: () =>
    typedError<string, AppError>(__TAURI_INVOKE('load_renderer_settings')),
  saveRendererSettings: (settings: string) =>
    typedError<boolean, AppError>(__TAURI_INVOKE('save_renderer_settings', { settings })),
  loadProfileSecrets: () => typedError<string, AppError>(__TAURI_INVOKE('load_profile_secrets')),
  saveProfileSecrets: (data: string) =>
    typedError<string, AppError>(__TAURI_INVOKE('save_profile_secrets', { data })),
  clearProfileSecrets: (profileId: string | null) =>
    typedError<boolean, AppError>(__TAURI_INVOKE('clear_profile_secrets', { profileId })),
  /**  Reads the job history JSON from disk so the frontend can populate the history tab. */
  getJobs: () => typedError<string, AppError>(__TAURI_INVOKE('get_jobs')),
  /**  Removes a specific job entry from the persistent history file. */
  deleteJob: (jobId: string) =>
    typedError<boolean, AppError>(__TAURI_INVOKE('delete_job', { jobId })),
  /**
   *  Opens a specific job's text log file in the native OS text editor.
   *
   *  Contains path traversal protection to prevent malicious UI requests from
   *  opening arbitrary system files.
   */
  openJobLog: (logPath: string) =>
    typedError<boolean, AppError>(__TAURI_INVOKE('open_job_log', { logPath })),
  /**
   *  Queries Roblox to resolve the creator of a batch of assets, emitting progress
   *  events to the UI so the user isn't staring at a frozen loading screen.
   */
  resolveAssetCreators: (assets: ResolverAsset[], cookie: string) =>
    typedError<ResolverAsset[], AppError>(
      __TAURI_INVOKE('resolve_asset_creators', { assets, cookie }),
    ),
  /**  Queries Roblox to filter out false-positive numeric IDs found inside scripts. */
  resolveScriptReferences: (assetIds: string[]) =>
    typedError<{ [key in string]: string }, AppError>(
      __TAURI_INVOKE('resolve_script_references', { assetIds }),
    ),
  /**  Validates if parsed asset IDs actually exist and what category they belong to. */
  validateAssetIds: (assetIds: string[]) =>
    typedError<{ [key in string]: string }, AppError>(
      __TAURI_INVOKE('validate_asset_ids', { assetIds }),
    ),
  /**  Pings Roblox to check for availability before proceeding with API calls. */
  checkRobloxApiStatus: () =>
    typedError<boolean, AppError>(__TAURI_INVOKE('check_roblox_api_status')),
  /**  Writes the React frontend's current state to disk. */
  saveSession: (session: string) =>
    typedError<null, AppError>(__TAURI_INVOKE('save_session', { session })),
  /**  Reads the previously saved UI state from disk. */
  loadSession: () => typedError<string | null, AppError>(__TAURI_INVOKE('load_session')),
  /**  Wipes the saved UI state, usually called during logout or when the user resets the app. */
  clearSession: () => typedError<null, AppError>(__TAURI_INVOKE('clear_session')),
  /**
   *  Reads a local Roblox place or model file and extracts all spoofable assets.
   *
   *  Supports both XML (`.rbxlx`, `.rbxmx`) and binary (`.rbxl`, `.rbxm`) formats.
   */
  parsePlaceFile: (filePath: string) =>
    typedError<PlaceParseResult, string>(__TAURI_INVOKE('parse_place_file', { filePath })),
  findStudioProcess: () => __TAURI_INVOKE<number | null>('find_studio_process'),
  focusAndSaveStudio: (pid: number) =>
    typedError<null, AppError>(__TAURI_INVOKE('focus_and_save_studio', { pid })),
  scanAndReplaceMultipleStrings: (pid: number, replacements: { [key in string]: string }) =>
    typedError<{ [key in string]: MemoryInjectionResult }, string>(
      __TAURI_INVOKE('scan_and_replace_multiple_strings', { pid, replacements }),
    ),
  clearAssetCache: () => __TAURI_INVOKE<boolean>('clear_asset_cache'),
  /**
   *  Configure the push URL for the community asset cache.
   *
   *  This sets the endpoint that newly discovered (asset_id, place_id) pairs are POSTed to.
   *  Reading from the community cache is explicitly NOT supported - users resolve assets
   *  from their own local session cache only.
   */
  initializeRemoteCache: (pushUrl: string | null) =>
    typedError<null, string>(__TAURI_INVOKE('initialize_remote_cache', { pushUrl })),
  patchAssetPermissions: (assetId: string, universeId: string, cookie: string, csrfToken: string) =>
    typedError<boolean, AppError>(
      __TAURI_INVOKE('patch_asset_permissions', { assetId, universeId, cookie, csrfToken }),
    ),
  setAssetPrivacy: (assetId: string, privacyStatus: string, cookie: string, csrfToken: string) =>
    typedError<boolean, AppError>(
      __TAURI_INVOKE('set_asset_privacy', { assetId, privacyStatus, cookie, csrfToken }),
    ),
  getPlaceIdFromCreator: (
    creatorType: string,
    creatorId: string,
    cookie: string,
    maxPlaceIds: number | null,
    placeName: string | null,
  ) =>
    typedError<string[], AppError>(
      __TAURI_INVOKE('get_place_id_from_creator', {
        creatorType,
        creatorId,
        cookie,
        maxPlaceIds,
        placeName,
      }),
    ),
  getMultiplePlaceIds: (
    creatorType: string,
    creatorId: string,
    cookie: string,
    maxPlaceIds: number | null,
    placeName: string | null,
  ) =>
    typedError<string[], AppError>(
      __TAURI_INVOKE('get_multiple_place_ids', {
        creatorType,
        creatorId,
        cookie,
        maxPlaceIds,
        placeName,
      }),
    ),
  discoverAssetPlaceId: (assetId: string, cookie: string, forcedPlaceId: string | null) =>
    typedError<string | null, AppError>(
      __TAURI_INVOKE('discover_asset_place_id', { assetId, cookie, forcedPlaceId }),
    ),
  getUniverseIdFromPlaceId: (placeId: string, cookie: string) =>
    typedError<string, AppError>(
      __TAURI_INVOKE('get_universe_id_from_place_id', { placeId, cookie }),
    ),
  searchGlobalPlaces: (keyword: string, limit: number | null) =>
    typedError<GlobalPlacesResponse, AppError>(
      __TAURI_INVOKE('search_global_places', { keyword, limit }),
    ),
  clearDownloadsDirectoryCommand: () =>
    typedError<boolean, AppError>(__TAURI_INVOKE('clear_downloads_directory_command')),
  findAssetByName: (cookie: string, assetType: string, name: string, groupId: string | null) =>
    typedError<string | null, AppError>(
      __TAURI_INVOKE('find_asset_by_name', { cookie, assetType, name, groupId }),
    ),
  /**
   *  Dispatches a mapping of original asset IDs to spoofed asset IDs directly into Roblox Studio.
   *
   *  Tries to use the high-performance memory bridge first. If the plugin isn't connected
   *  to the bridge, it falls back to a direct local HTTP POST.
   */
  pushToStudio: (replacementsMap: string, pluginPort: string | null) =>
    typedError<string, AppError>(__TAURI_INVOKE('push_to_studio', { replacementsMap, pluginPort })),
  setPluginThemeAccent: (color: string) =>
    typedError<null, string>(__TAURI_INVOKE('set_plugin_theme_accent', { color })),
  /**
   *  Toggles whether the plugin should skip checking if the user actually owns the assets.
   *
   *  This is used during testing or offline spoofing scenarios.
   */
  setBridgeSkipOwnedCheck: (skipOwned: boolean) =>
    __TAURI_INVOKE<boolean>('set_bridge_skip_owned_check', { skipOwned }),
  /**  Returns the ephemeral port the bridge server successfully bound to. */
  getPluginBridgePort: () => __TAURI_INVOKE<number | null>('get_plugin_bridge_port'),
  /**  Checks if the Studio plugin has polled the daemon recently. */
  getStudioHealthStatus: () => __TAURI_INVOKE<string>('get_studio_health_status'),
  /**
   *  Reports whether the plugin HTTP server landed on its default ports or had to
   *  move past them, and which processes are occupying the defaults.
   */
  getPortDiagnostic: () => __TAURI_INVOKE<string>('get_port_diagnostic'),
  /**  Returns the current state of asset discovery for the frontend UI. */
  getStudioAssetSnapshots: () => __TAURI_INVOKE<string>('get_studio_asset_snapshots'),
};

/* Types */
export type ApiKeyOwnerDetectResult = {
  ok: boolean;
  ownerUserId: string | null;
  message: string;
};

/**
 *  Centralized application error enum.
 *
 *  This type is exported to the frontend via Specta and serialized into a structured
 *  JSON string containing both a user-facing message and debug details. It wraps
 *  common underlying errors (IO, Network, JSON) to avoid scattered `.unwrap()` calls.
 */
export type AppError = string;

export type AssetExplorerItem = {
  id: number | null;
  name: string;
  type: string;
  created: string | null;
  updated: string | null;
  thumbnailUrl: string | null;
  creatorType: string;
  creatorId: string;
  isModerated: boolean;
};

export type FetchAssetsRequest = {
  creatorType: string | null;
  creatorId: string;
  assetTypes: string[] | null;
  cookie: string;
  limit: number | null;
  maxPages: number | null;
};

export type FetchAssetsResponse = {
  total: number;
  items: AssetExplorerItem[];
};

export type GlobalPlace = {
  creatorId: number | null;
  creatorName: string;
  creatorType: string;
  universeId: number | null;
  name: string;
  placeId: number | null;
};

export type GlobalPlacesResponse = {
  previousPageCursor: string | null;
  nextPageCursor: string | null;
  games: GlobalPlace[];
};

export type MemoryInjectionResult = {
  utf8_replaced: number;
  utf16_replaced: number;
  total_replaced: number;
};

export type NotificationOptions = {
  title: string | null;
  body: string | null;
};

export type ParsedAssetRef = {
  type: string;
  assetId: string;
  rawValue: string;
  className: string;
  instanceName: string;
  propertyName: string;
  path: string;
};

export type PlaceParseResult = {
  fileType: string;
  rootInstances: RbxInstance[];
  warnings: string[];
};

export type ProfileRequest = {
  autoDetect: boolean | null;
  cookie: string | null;
  groupId: string | null;
};

export type RbxInstance = {
  referent: string;
  className: string;
  name: string;
  assets: ParsedAssetRef[];
  children: RbxInstance[];
};

export type ResolverAsset = {
  assetId: string;
  name: string | null;
  creator: string | null;
  creatorId: string | null;
  creatorType: string | null;
};

/**  The root structure of a Roblox animation containing all keyframes. */
export type RobloxAnimationClip = {
  loop: boolean;
  priority: number;
  duration: number | null;
  keyframes: RobloxKeyframe[];
};

export type RobloxGroup = {
  id: number | null;
  name: string;
};

/**  A specific moment in time within an animation clip. */
export type RobloxKeyframe = {
  time: number | null;
  poses: RobloxPose[];
};

/**  Represents a single joint/bone's transform at a specific point in time. */
export type RobloxPose = {
  name: string;
  position: [number | null, number | null, number | null];
  rotation: [
    number | null,
    number | null,
    number | null,
    number | null,
    number | null,
    number | null,
    number | null,
    number | null,
    number | null,
  ];
  children: RobloxPose[];
  easingStyle: number;
  easingDirection: number;
};

export type RobloxUserInfo = {
  id: number | null;
  name: string;
  displayName: string;
};

export type SpooferActionRequest = {
  assets: string | null;
  cookie: string | null;
  fallbackCookies: string[] | null;
  apiKey: string | null;
  groupId: string | null;
  spoofSounds: boolean | null;
  uploadTypes: string[] | null;
  downloadPath: string | null;
  forcePlaceIds: string | null;
  assetForcePlaceIds: { [key in string]: string } | null;
  operationPollIntervalMs: number | null;
  placeName: string | null;
  concurrent: boolean | null;
  concurrentDownloading: boolean | null;
  maxConcurrency: number | null;
  maxDownloadConcurrency: number | null;
  skipOwned: boolean | null;
  excludedUserIds: string | null;
  excludedGroupIds: string | null;
  skipExistingReplacements: boolean | null;
  existingReplacements: string | null;
  account: string | null;
  group: string | null;
  preserveMetadata: boolean | null;
  enableArchiveRecovery: boolean | null;
  proxyUrl: string | null;
};

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: 'ok'; data: T } | { status: 'error'; error: E }> {
  try {
    return { status: 'ok', data: await result };
  } catch (e) {
    if (e instanceof Error) throw e;
    return { status: 'error', error: e as any };
  }
}
